### PR TITLE
Add previous information of club

### LINKED ISSUE #25: Add previous information of the club
**Describe the bug/feature**

The information about the former board of directors of the club should be there. A separate page should be created having url something like, `https://rtrclubiitj.github.io/former_boards`.

**To Reproduce(for bug)**

**Screenshots(for bug)**

**Device Details(for bug)**

**Other Comments**

@Saptashrungi Please fix this issue.

### PR DESCRIPTION
**Pull request by Saptashrungi**
Added a folder for Former boards
Fixes #25

### CODE REVIEW

**Comment by Saptashrungi** [comment]
@czgdp1807  created a folder

**Comment by czgdp1807** [comment]
Changes to be made on top of the previous ones

1. Remove the `Former_Boards` and replace it with a file, `former_boards.md`.
2. Make some changes to `_includes/nav.html` so that, `http://127.0.0.1:4000/former_boards` works. Have you installed jekyll and its dependencies on your system?

**Comment by czgdp1807** [comment]
Ah! again a PR from `master`? Please close this one and make a PR from some different branch.

**Comment by Saptashrungi** [comment]
Jekyll download is left

**Pull request closed without merging**
