### PR TITLE
Added blog entry for the minutes of meetings

### PR DESCRIPTION
**Pull request by Saptashrungi**
The blog for minutes of latest meeting have been added in latest commit. PR is for the same.

### CODE REVIEW

**Comment by Saptashrungi** [comment]
ping @czgdp1807

**Comment by czgdp1807** [comment]
Thanks for the PR.
Changes to be made

1. Add `Fixes #12` in [the description](https://github.com/rtrclubiitj/rtrclubiitj.github.io/pull/16#issue-308317949).
2. Rename the file from `board_meeting.txt` to `2019-08-18-post_8.md`
3. Replace `Pull Request template for board meeting` in the title of this PR to `Added blog entry for minutes of meetings`.
4. Add YAML front matter similar to the one given below,
```
---
layout: post
title:  "Celeberating Deepawali"
date:   2018-11-08
author: ""
excerpt: "On the auspicious occasion of Deepawali, we along with Social Service Club of IIT Jodhpur, went to the labor camp to celebrate the festival."
image: "/images/post_1.jpg"
is_pinned: false
---
```
You should not copy and paste the above YAML information, instead edit according to the post.

Suggestions for future PRs

1. Write short descriptive commit messages like, `added minutes of meetings`.
2. Use more meaningful branch names like, `blog-entry-mom`.
3. Do not remove the template which shows up in the description when you compare across forks.

**Comment by Saptashrungi** [comment]
what have i to do to add fixes in the description?

**Comment by czgdp1807** [comment]
Well, just edit [the comment](https://github.com/rtrclubiitj/rtrclubiitj.github.io/pull/16#issue-308317949) and write Fixes #12

**Pull request closed without merging**
