### PR TITLE
Added former board details

### LINKED ISSUE #25: Add previous information of the club
**Describe the bug/feature**

The information about the former board of directors of the club should be there. A separate page should be created having url something like, `https://rtrclubiitj.github.io/former_boards`.

**To Reproduce(for bug)**

**Screenshots(for bug)**

**Device Details(for bug)**

**Other Comments**

@Saptashrungi Please fix this issue.

### PR DESCRIPTION
**Pull request by czgdp1807**
#### Type of Change:

- [x] Code
- [ ] Blog
- [x] Club Structure

#### Description

Fixes #25  
Closes #28 

#### Other comments

References https://docs.google.com/spreadsheets/d/19sQEqM5JEn7kOqXlaYOXM05z7Ft_6Q3FJcn4JQD_oWw/edit?usp=sharing
ping @sonaljaiswal It will be merged within one hour since the associated work is stalled from a very long time. Please let me know until then if any suggestions you have. Thanks.

### CODE REVIEW

**Comment by sonaljaiswal** [comment]
I don't understand that there are less than 50 registered members sent in
the list by Kr. Rahul sir and I have 95 certificates to be distributed.

**Comment by czgdp1807** [comment]
Well that issue is not related with this PR.

**Comment by sonaljaiswal** [comment]
But should we upload this, if there are discrepancies?! I don't think so. I
will have to clarify it with the ex -president. Kindly wait for sometime.

**Comment by sonaljaiswal** [comment]
It seems you have done it. It's okay.let it be. I hope we can edit it after
corrections.

**Comment by czgdp1807** [comment]
The list has been verified by the previous president as discussed on the WhatsApp group. I think now there are no more points to discuss

**Comment by sonaljaiswal** [comment]
You may proceed.

**Pull request merged**
