### PR TITLE
Added minutes of meeting

### PR DESCRIPTION
**Pull request by Saptashrungi**
The latest minutes of the meeting held on 20 Sep have been added.

### CODE REVIEW

**Comment by czgdp1807** [comment]
Where is the YAML front matter? Something like the following,
```
---
layout: post
title:  "BOARD OF DIRECTORS MEETING"
date:   2019-08-12
author: ""
excerpt: "Progressive minds focus on ideas."
image: ""
is_pinned: true
---
```
Refer, https://raw.githubusercontent.com/rtrclubiitj/rtrclubiitj.github.io/master/_posts/2019-08-12-mom_1.md
Please post a screenshot by building the website locally. Refer, https://github.com/rtrclubiitj/rtrclubiitj.github.io#how-to-use-this-theme

**Comment by Saptashrungi** [comment]
@czgdp1807  I edited the mom file and sent a new PR.

**Comment by czgdp1807** [comment]
Have you tried to build the website, locally?

**Comment by Saptashrungi** [comment]
No...I haven't begun with Jekyll yet

**Comment by czgdp1807** [comment]
@asharani97 Please make a new PR for uploading the minutes of meetings.

**Pull request closed without merging**
